#!/bin/sh

setup() {
    LD_LIBRARY_PATH=/usr/local/lib:/usr/lib
    PATH=/opt/ruby/2.0/bin:/opt/ruby/1.9.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
    APP_DIR=/var/www/rails/repo_manager
}

update() {
    cd $APP_DIR
    git pull
    bundle exec rake assets:precompile RAILS_ENV=production
    # bundle exec rake db:migrate RAILS_ENV=production
    rm -rf tmp/*
    chown -R apache:apache . && sudo chmod -R g+w,o-rwx .
    cp -Rv /var/lib/rails/service_portal/html/* /var/www/html/
}

main() {
    setup
    update
    service httpd restart
}

main
exit 0
